name: Build PIDsim Installers

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set package type
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then echo "TYPE=DEB" >> $GITHUB_ENV; fi
          if [ "$RUNNER_OS" == "Windows" ]; then echo "TYPE=EXE" >> $GITHUB_ENV; fi
          if [ "$RUNNER_OS" == "macOS" ]; then echo "TYPE=DMG" >> $GITHUB_ENV; fi

      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y fakeroot dpkg-dev rpm

      - name: Build
        working-directory: pid-motor-sim
        run: mvn clean package -Djpackage.type=$TYPE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PIDsim-${{ runner.os }}
          path: pid-motor-sim/target/installer/*
